#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=10000MB
#PBS -l vmem=10000MB
#PBS -l pmem=10000MB
#PBS -l walltime=24:00:00
#PBS -q cmb
#!/bin/bash
cd "$PBS_O_WORKDIR"


/home/cmb-panasas2/decato/bin/methpipe/bin/roimethstat -L -o ${IN}.inPMDs.roimethstat ${UNION} ${IN}
/home/cmb-panasas2/decato/bin/methpipe/bin/roimethstat -L -o ${IN}.outPMDs.roimethstat ${DIFFERENCE} ${IN}


#/home/cmb-panasas2/decato/bin/methpipe/bin/roimethstat -L -o ${IN}.pmds $(dirname ${IN})/$(basename ${IN} .meth).pmd ${IN}
